### ISSUE TITLE
Parameterize `README.MD`

### ISSUE THREAD

**Issue by CobyPear** [pantheon-systems/plugin-release-actions#2]
README.MD should be parameterized with a default value of README.MD in case it's not uppercase in every repo (or make this case-insensitive but that might be troublesome in a one-liner.

_Originally posted by @pwtyler in https://github.com/pantheon-systems/plugin-release-actions/pull/1#discussion_r1433124967_

**Comment by pwtyler** [comment]
@jazzsequence addressed this
https://github.com/pantheon-systems/plugin-release-actions/commit/e03d01bf04d9ca99e4fb5dc75a4a05a3c8aaf75f
